// PostgreSQL built-in type OIDs used throughout the client package.

///|
const BOOL_OID : @proto.Oid = 16U

///|
const BYTEA_OID : @proto.Oid = 17U

///|
const CHAR_OID : @proto.Oid = 18U

///|
const NAME_OID : @proto.Oid = 19U

///|
const INT8_OID : @proto.Oid = 20U

///|
const INT2_OID : @proto.Oid = 21U

///|
const INT4_OID : @proto.Oid = 23U

///|
const TEXT_OID : @proto.Oid = 25U

///|
const OID_TYPE_OID : @proto.Oid = 26U

///|
const JSON_OID : @proto.Oid = 114U

///|
const FLOAT4_OID : @proto.Oid = 700U

///|
const FLOAT8_OID : @proto.Oid = 701U

///|
const VARCHAR_OID : @proto.Oid = 1043U

///|
const DATE_OID : @proto.Oid = 1082U

///|
const TIME_OID : @proto.Oid = 1083U

///|
const TIMESTAMP_OID : @proto.Oid = 1114U

///|
const TIMESTAMPTZ_OID : @proto.Oid = 1184U

///|
const UUID_OID : @proto.Oid = 2950U

///|
const JSONB_OID : @proto.Oid = 3802U

///|
const BOOL_ARRAY_OID : @proto.Oid = 1000U

///|
const BYTEA_ARRAY_OID : @proto.Oid = 1001U

///|
const INT2_ARRAY_OID : @proto.Oid = 1005U

///|
const INT4_ARRAY_OID : @proto.Oid = 1007U

///|
const TEXT_ARRAY_OID : @proto.Oid = 1009U

///|
const VARCHAR_ARRAY_OID : @proto.Oid = 1015U

///|
const INT8_ARRAY_OID : @proto.Oid = 1016U

///|
const FLOAT4_ARRAY_OID : @proto.Oid = 1021U

///|
const FLOAT8_ARRAY_OID : @proto.Oid = 1022U

///|
const TIMESTAMP_ARRAY_OID : @proto.Oid = 1115U

///|
const DATE_ARRAY_OID : @proto.Oid = 1182U

///|
const UUID_ARRAY_OID : @proto.Oid = 2951U
