name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4

      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: install integration test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl postgresql postgresql-client

      - name: moon version
        run: |
          moon version --all

      - name: moon update
        run: |
          moon update

      - name: moon check
        run: moon check

      - name: format diff
        run: |
          moon fmt
          git diff --exit-code

      - name: postgres integration test
        run: |
          ulimit -s 8176
          node scripts/pg_integration_test.mjs
